- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/AuthController.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/Signup.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/SignUpRepository.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/AuthService.java
> feat: ajoute l'activation d'un utilisateur en base de données

- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/AuthController.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/exception/ImplicactionException.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/exception/ImplicitActionException.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/AuthService.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/MailService.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/util/Constants.java
* renommage de la classe ImplicitactionException en ImplicactionException
* factorisation de différentes méthodes dans le service auth
> refact: ajoute différentes amélioration et qques fix

- backend-implicaction/pom.xml
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/config/SecurityConfig.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/FakeController.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/FakeDto.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/security/JwtAuthenticationFilter.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/security/JwtProvider.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/AuthService.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/FakeService.java
* création d'un filter pour la validation du token
> feat: ajoute la validation du token jwt

- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/AuthenticationResponseDto.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/LoginRequestDto.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/RefreshTokenRequestDto.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/ReqisterRequestDto.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/Signup.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/User.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/SignUpRepository.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/UserRepository.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/AuthService.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/FakeService.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/UserDetailsServiceImpl.java
- frontend-implicaction/package-lock.json
- frontend-implicaction/package.json
- frontend-implicaction/src/app/app.module.ts
- frontend-implicaction/src/app/auth/auth-routing.module.ts
- frontend-implicaction/src/app/auth/auth.module.ts
- frontend-implicaction/src/app/auth/components/login/login.component.html
- frontend-implicaction/src/app/auth/components/login/login.component.scss
- frontend-implicaction/src/app/auth/components/login/login.component.spec.ts
- frontend-implicaction/src/app/auth/components/login/login.component.ts
- frontend-implicaction/src/app/auth/components/signup/signup.component.html
- frontend-implicaction/src/app/auth/models/login-request-payload.ts
- frontend-implicaction/src/app/auth/models/login-response.ts
- frontend-implicaction/src/app/auth/services/auth.service.ts
* uniformise les tous les champs login/username en username
Closes #18
> feat: ajoute le formulaire de login

- backend-implicaction/pom.xml
- frontend-implicaction/src/app/auth/components/login/login.component.ts
- pom.xml
> fix: corrige les poms pour que le projet puisse se lancer à l'aide de la commande mvn spring-boot:run

- frontend-implicaction/src/app/auth/components/login/login.component.html
- frontend-implicaction/src/app/auth/components/login/login.component.ts
- frontend-implicaction/src/app/auth/components/signup/signup.component.html
- frontend-implicaction/src/app/auth/components/signup/signup.component.ts
- frontend-implicaction/src/app/auth/services/auth.service.ts
- frontend-implicaction/src/app/core/services/toaster.service.spec.ts
- frontend-implicaction/src/app/core/services/toaster.service.ts
* redirige à l'accueil si login success et affiche un toaster
* affiche un message d'erreur si login error
* redirige vers le formulaire de login si signup success
* affiche un message d'erreur si signup error
Closes #12
> feat: redirige l'utilisateur lors d'un login/signup

- backend-implicaction/pom.xml
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/repository/AbstractContainerBaseTest.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/repository/UserRepositoryTest.java
* ajout des dépendances aux TestContainers
* test de la méthode save
* test de la méthode findByUsername
> test: ajoute les tests pour le UserRepository

- backend-implicaction/pom.xml
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/RefonteImplicactionApplication.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/config/SecurityConfig.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/config/SwaggerConfiguration.java
> doc: ajoute les dépendances swagger et swagger-ui et implémente leur utilisation

- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/config/SecurityConfig.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/ForwardController.java
- frontend-implicaction/src/app/auth/components/login/login.component.html
- frontend-implicaction/src/app/auth/components/login/login.component.ts
> fix: corrige l'erreur whitelabel lors du refresh d'une page

- frontend-implicaction/src/app/core/services/api-endpoints.service.ts
- frontend-implicaction/src/app/shared/models/uris.ts
> feat: centralise les URI vers l'api dans la classe Uris

- frontend-implicaction/src/app/admin/guards/admin.guard.ts
- frontend-implicaction/src/app/auth/components/login/login.component.html
- frontend-implicaction/src/app/auth/components/login/login.component.ts
- frontend-implicaction/src/app/core/interceptors/jwt.interceptor.ts
* correction d'un bug : une demande de refresh token était envoyé lors d'un echec du login
* refacto des alertes de login pour permettre plusieurs type de message (login fail, signup success)
> feat: redirige l'utilisateur lorsqu'un login est nécessaire pout accéder à la page souhaitée

- frontend-implicaction/src/app/auth/components/login/login.component.ts
- frontend-implicaction/src/app/auth/components/signup/signup.component.ts
> feat: empêche les utilisateurs d'accéder aux pages signup et login s'ils sont déjà loggés

- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/config/SwaggerConfiguration.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/UserController.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/ExceptionResponse.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/exception/ImplicactionException.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/exception/UnauthorizedException.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/handler/GlobalExceptionHandler.java
- frontend-implicaction/src/app/admin/users/components/users-table/table-users.component.ts
> feat: ajoute la gestion des exceptions de l'api

- frontend-implicaction/package-lock.json
- frontend-implicaction/package.json
- frontend-implicaction/src/app/admin/guards/Logged-in.guard.spec.ts
- frontend-implicaction/src/app/admin/guards/logged-in.guard.ts
- frontend-implicaction/src/app/admin/users/components/users-table/table-users.component.html
- frontend-implicaction/src/app/admin/users/components/users-table/table-users.component.scss
- frontend-implicaction/src/app/admin/users/components/users-table/table-users.component.ts
- frontend-implicaction/src/app/app-routing.module.ts
- frontend-implicaction/src/app/app.component.html
- frontend-implicaction/src/app/app.component.scss
- frontend-implicaction/src/app/community/community-routing.module.ts
- frontend-implicaction/src/app/community/community.component.html
- frontend-implicaction/src/app/community/community.component.scss
- frontend-implicaction/src/app/community/community.component.spec.ts
- frontend-implicaction/src/app/community/community.component.ts
- frontend-implicaction/src/app/community/community.module.ts
- frontend-implicaction/src/app/config/constants.ts
- frontend-implicaction/src/app/icons/icons.module.ts
- frontend-implicaction/src/app/shared/components/header/header.component.html
- frontend-implicaction/src/app/shared/components/header/header.component.scss
- frontend-implicaction/src/app/shared/components/user-card/user-card.component.html
- frontend-implicaction/src/app/shared/components/user-card/user-card.component.scss
- frontend-implicaction/src/app/shared/components/user-card/user-card.component.spec.ts
- frontend-implicaction/src/app/shared/components/user-card/user-card.component.ts
- frontend-implicaction/src/app/shared/models/pageable.ts
- frontend-implicaction/src/app/shared/models/user.ts
- frontend-implicaction/src/app/shared/shared.module.ts
- frontend-implicaction/src/assets/variables.scss
- frontend-implicaction/src/styles.scss
* installation de la lib feather-icon
* refact de l'interface pageable : ajout de rowsPerPages
* modification de la couleur primary bootstrap
* ajout d'un background au body
> feat: ajoute la page communauté

- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/adapter/RelationAdapter.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/adapter/UserAdapter.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/RelationController.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/UserController.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/RelationsDto.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/UserDto.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/Group.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/Relation.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/Signup.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/Training.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/User.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/WorkExperience.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/RelationRepository.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/AuthService.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/RelationService.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/adapter/RelationAdapterTest.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/adapter/TrainingAdapterTest.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/adapter/UserAdapterTest.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/adapter/WorkExperienceAdapterTest.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/repository/RelationRepositoryTest.java
- frontend-implicaction/package-lock.json
- frontend-implicaction/package.json
- frontend-implicaction/src/app/community/community.component.html
- frontend-implicaction/src/app/core/services/api-endpoints.service.ts
- frontend-implicaction/src/app/shared/models/uris.ts
* création du modèle relation (classe model, dto, adapter, service)
* création du service relation
* suppression des annotations @Data
* ajout des tests RelationAdapter et Repository
* ajout de la dépendance de développement eslint
Closes #13
> feat(relations): permet l'ajout et la recherche de relations

- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/RelationController.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/RelationRepository.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/RelationService.java
* correction de la recherche d'amis qui recherche désormais un utilisateur en sender et receiver (avant seul le sender était vérifié)
> refact(relations): modifie les routes du contrôleur relation pour correspondre au pattern /relations/operation/:userId

- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/RelationController.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/RelationRepository.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/RelationService.java
- frontend-implicaction/src/app/core/services/api-endpoints.service.ts
- frontend-implicaction/src/app/icons/icons.module.ts
- frontend-implicaction/src/app/shared/models/uris.ts
- frontend-implicaction/src/app/user/components/experience-list/experience-list.component.html
- frontend-implicaction/src/app/user/components/user-list/user-list.component.html
- frontend-implicaction/src/app/user/components/user-list/user-list.component.scss
- frontend-implicaction/src/app/user/components/user-list/user-list.component.ts
- frontend-implicaction/src/app/user/models/relation.ts
- frontend-implicaction/src/app/user/services/relation.service.spec.ts
- frontend-implicaction/src/app/user/services/relation.service.ts
- frontend-implicaction/src/assets/variables.scss
- frontend-implicaction/src/styles.scss
* la récupération de la liste des relation n'est plus paginée
* renvoie d'une exception lorsque le sender et le receiver sont les mêmes user
* modification du template de la liste des utilisateurs pour permettre l'ajout, la suppression et la confirmation d'une demande d'ami
> feat(user/relation): permet d'effectuer une demande d'ami en cliquant sur "ajouter" depuis la liste des membres

- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/RelationController.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/exception/NotFoundException.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/handler/GlobalExceptionHandler.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/RelationRepository.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/UserRepository.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/AuthService.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/RelationService.java
* création de la NotFoundException
* mapping de l'exception dans le GlobalExceptionHandler
* modifie le type de retour de AuthService::getCurrentUser en UserDto
> feat(user/relation): permet à l'api de supprimer une demande d'ami à l'aide d'un senderId

- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/adapter/UserAdapter.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/UserDto.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/User.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/adapter/UserAdapterTest.java
* ajout des champs  purpose, presentation, expectation, contribution, first_name, last_name
* portage des modifications dans le dto / adapter / tests
> refact: complète le modèle user

- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/config/SecurityConfig.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/RelationController.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/UserController.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/RelationTypeEnum.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/UserDto.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/RelationRepository.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/AuthService.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/RelationService.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/UserService.java
- frontend-implicaction/src/app/shared/models/user.ts
- frontend-implicaction/src/app/user/components/user-list/user-list.component.html
- frontend-implicaction/src/app/user/components/user-list/user-list.component.ts
- frontend-implicaction/src/app/user/models/relation-type.enum.ts
* introduction d'une enum TypeRelation dans le UserDto pour introduire la notion de SENDER, RECEIVER, FRIEND dans le cadre d'une relation
> [RI-23]: modifie la recherche de tous les utilisateurs pour ne plus avoir à récupérer la liste de toutes les relations

- frontend-implicaction/src/app/shared/components/loading/loading.component.html
- frontend-implicaction/src/app/shared/components/loading/loading.component.scss
- frontend-implicaction/src/app/shared/components/loading/loading.component.spec.ts
- frontend-implicaction/src/app/shared/components/loading/loading.component.ts
- frontend-implicaction/src/app/shared/shared.module.ts
- frontend-implicaction/src/app/user/components/user-list/user-list.component.html
- frontend-implicaction/src/app/user/components/user-list/user-list.component.scss
- frontend-implicaction/src/app/user/components/user-list/user-list.component.ts
- frontend-implicaction/src/app/user/user.module.ts
* modification du nombre de card affichés par ligne et de la taille du menu en fonction de la taille de la fenêtre / écran
* remplace la cascade de ngif -- else par un ngswitch
* correction du paginator
* création d'un composant spinner
* affichage du spinner lors du chargement de la liste des utilisateurs
> refact(user/list): corrige le responsive de la page

- frontend-implicaction/src/app/user/components/personal-card/personal-card.component.html
- frontend-implicaction/src/app/user/components/personal-card/personal-card.component.scss
- frontend-implicaction/src/app/user/components/user-profile/user-profile.component.html
* le composant personal-card n'est plus lié au user-card
https://user-images.githubusercontent.com/4210719/134030336-e4075c11-5b07-4b64-9b71-6462b46f7dc7.mov
> RI-56: corrige le responsive du profil utilisateur

- frontend-implicaction/src/app/auth/components/unauthorized/unauthorized.component.html
- frontend-implicaction/src/app/auth/components/unauthorized/unauthorized.component.scss
> RI-57: Créer la page unauthorized

- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/adapter/WorkExperienceAdapter.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/WorkExperienceDto.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/WorkExperience.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/adapter/TrainingAdapterTest.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/adapter/UserAdapterTest.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/adapter/WorkExperienceAdapterTest.java
- frontend-implicaction/src/app/core/services/api-endpoints.service.ts
- frontend-implicaction/src/app/icons/icons.module.ts
- frontend-implicaction/src/app/shared/models/uris.ts
- frontend-implicaction/src/app/shared/models/work-experience.ts
- frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.html
- frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.scss
- frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.ts
- frontend-implicaction/src/app/user/components/experience-list/experience-list.component.html
- frontend-implicaction/src/app/user/components/experience-list/experience-list.component.ts
- frontend-implicaction/src/app/user/components/user-profile/user-profile.component.html
- frontend-implicaction/src/app/user/services/user.service.ts
- frontend-implicaction/src/app/user/user.module.ts
- frontend-implicaction/src/assets/variables.scss
> RI-22: ajoute le mode edition des experiences

- frontend-implicaction/src/app/core/services/api-endpoints.service.ts
- frontend-implicaction/src/app/user/components/training-detail/training-detail.component.html
- frontend-implicaction/src/app/user/components/training-detail/training-detail.component.scss
- frontend-implicaction/src/app/user/components/training-detail/training-detail.component.ts
- frontend-implicaction/src/app/user/components/training-list/training-list.component.html
- frontend-implicaction/src/app/user/components/training-list/training-list.component.ts
- frontend-implicaction/src/app/user/components/user-profile/user-profile.component.html
- frontend-implicaction/src/app/user/services/user.service.ts
- frontend-implicaction/src/app/user/user.module.ts
> RI-21: permet d'éditer les formations

- frontend-implicaction/src/app/icons/icons.module.ts
- frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.html
- frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.scss
- frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.ts
- frontend-implicaction/src/app/user/components/experience-list/experience-list.component.html
- frontend-implicaction/src/app/user/components/experience-list/experience-list.component.ts
On peut dès a présent supprimer un élément de la liste des expériences en cliquant sur la corbeille puis en cliquant sur save.
Dans le cas ou on rollback l'expérience n'est pas supprimé.
> RI-26: supprime des expériences dans le mode édition

- frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.html
- frontend-implicaction/src/app/user/components/experience-detail/experience-detail.component.ts
- frontend-implicaction/src/app/user/components/experience-list/experience-list.component.html
- frontend-implicaction/src/app/user/components/experience-list/experience-list.component.scss
- frontend-implicaction/src/app/user/components/experience-list/experience-list.component.ts
* ajoute une propriété sur le calendar pour que l'on puisse selectionner les années
* ajoute une propriété sur le calendar pour qu'il s'affiche en entier sur le body
> RI-69: Ajouter des expériences dans le mode édition

- frontend-implicaction/src/app/icons/icons.module.ts
- frontend-implicaction/src/app/user/components/training-detail/training-detail.component.html
- frontend-implicaction/src/app/user/components/training-detail/training-detail.component.ts
- frontend-implicaction/src/app/user/components/training-list/training-list.component.html
- frontend-implicaction/src/app/user/components/training-list/training-list.component.ts
> RI-25: supprimer une formation

- frontend-implicaction/src/app/user/components/training-detail/training-detail.component.html
- frontend-implicaction/src/app/user/components/training-list/training-list.component.html
- frontend-implicaction/src/app/user/components/training-list/training-list.component.scss
- frontend-implicaction/src/app/user/components/training-list/training-list.component.ts
> RI-70: ajouter une formation

- frontend-implicaction/src/app/app.component.html
- frontend-implicaction/src/app/app.component.scss
- frontend-implicaction/src/assets/toaster.scss
- frontend-implicaction/src/index.html
> RI-72: modifie le design du toaster ainsi que ses transitions.

- frontend-implicaction/src/app/shared/classes/utils.spec.ts
- frontend-implicaction/src/app/shared/classes/utils.ts
- frontend-implicaction/src/app/user/components/experience-list/experience-list.component.html
- frontend-implicaction/src/app/user/components/experience-list/experience-list.component.ts
- frontend-implicaction/src/app/user/components/training-list/training-list.component.html
- frontend-implicaction/src/app/user/components/training-list/training-list.component.ts
On peut maintenant ajouter qu'un élément vide dans une expérience ou une formation.
> fix: corrige le problème d'ajout d'un nouvel element en le bloquant à un element vide maximum

- data.sql
Valeurs des tables manquantes lors du dump
> fix: dump de la BD

- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/UserController.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/UserService.java
Permet de sauvegarder les informations du profil d'un utilisateur (_Job Seeker_ ou _Recruiter_) dans la base de données.
> RI-29: sauvegarde les informations personnelles dans la BD

- frontend-implicaction/src/app/shared/components/header/header.component.html
- frontend-implicaction/src/app/shared/components/header/header.component.scss
> RI-91: Ajoute un @username dans le menu déroulant du header.

- frontend-implicaction/src/app/shared/components/header/header.component.html
- frontend-implicaction/src/app/shared/components/header/header.component.scss
- frontend-implicaction/src/styles.scss
…à un lien alors qu'il ne s'agit que de texte.
> RI-102: corrige le problème du username dans le menu de la barre de navigation qui ressemble à un lien alors qu'il ne s'agit que de texte

- backend-implicaction/pom.xml
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/adapter/SubredditAdapter.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/AuthController.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/JobPostingController.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/RelationController.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/SubredditController.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/RefreshTokenRequestDto.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/SubredditDto.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/Post.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/Subreddit.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/User.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/SubredditRepository.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/AuthService.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/SubredditService.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/utils/ApiUrls.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/RefonteImplicactionApplicationTests.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/adapter/SubredditAdapterTest.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/SubredditControllerIntegrationTest.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/service/GroupServiceTest.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/service/SubredditServiceTest.java
* création de la classe qui contient les breakpoints des controllers
* monté de version jakarta.validation, org.testcontainers.mysql, springfox-swagger2, springfox-swagger-ui
> RI-144: ajoute le back pour les Subreddits

- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/CompanyController.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/CompanyService.java
- frontend-implicaction/src/app/admin/admin.module.ts
- frontend-implicaction/src/app/admin/companies/companies.component.html
- frontend-implicaction/src/app/admin/companies/companies.component.ts
- frontend-implicaction/src/app/admin/companies/companies.module.ts
- frontend-implicaction/src/app/admin/companies/components/companies-form/companies-form.component.html
- frontend-implicaction/src/app/admin/companies/components/companies-form/companies-form.component.spec.ts
- frontend-implicaction/src/app/admin/companies/components/companies-form/companies-form.component.ts
- frontend-implicaction/src/app/admin/companies/components/companies-table/companies-table.component.html
- frontend-implicaction/src/app/admin/companies/components/companies-table/companies-table.component.ts
- frontend-implicaction/src/app/company/services/company.service.ts
- frontend-implicaction/src/app/core/services/api-endpoints.service.ts
- frontend-implicaction/src/app/shared/models/sidebar-props.ts
> RI-64: ajout et modification d'une entreprise via sidebar

- frontend-implicaction/src/app/admin/jobs/admin-jobs.component.ts
- frontend-implicaction/src/app/admin/jobs/components/job-posting-form/job-posting-form.component.html
- frontend-implicaction/src/app/admin/jobs/components/job-posting-form/job-posting-form.component.ts
- frontend-implicaction/src/app/shared/services/sidebar.service.ts
- frontend-implicaction/src/styles.scss
* suppression du box-shadow des boutons
> fix: corrige le bug lié à l'appel de la méthode updateFields lors de la création d'un job

- frontend-implicaction/src/app/admin/companies/components/companies-form/companies-form.component.ts
> RI-146 : mise à jour du tableau de compagnie après édition d'une compagnie

- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/adapter/PostAdapter.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/config/SecurityConfig.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/PostResponse.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/model/Post.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/adapter/PostAdapterTest.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/PostControllerIntegrationTest.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/service/PostServiceTest.java
- frontend-implicaction/src/app/app-routing.module.ts
- frontend-implicaction/src/app/blog/blog-routing.module.ts
- frontend-implicaction/src/app/blog/blog.component.html
- frontend-implicaction/src/app/blog/blog.component.spec.ts
- frontend-implicaction/src/app/blog/blog.component.ts
- frontend-implicaction/src/app/blog/blog.module.ts
- frontend-implicaction/src/app/blog/components/post-details/post-details.component.html
- frontend-implicaction/src/app/blog/components/post-details/post-details.component.scss
- frontend-implicaction/src/app/blog/components/post-details/post-details.component.spec.ts
- frontend-implicaction/src/app/blog/components/post-details/post-details.component.ts
- frontend-implicaction/src/app/blog/components/post-list/post-list.component.html
- frontend-implicaction/src/app/blog/components/post-list/post-list.component.spec.ts
- frontend-implicaction/src/app/blog/components/post-list/post-list.component.ts
- frontend-implicaction/src/app/blog/components/votebox/votebox.component.html
- frontend-implicaction/src/app/blog/components/votebox/votebox.component.spec.ts
- frontend-implicaction/src/app/blog/components/votebox/votebox.component.ts
- frontend-implicaction/src/app/blog/model/post.ts
- frontend-implicaction/src/app/blog/services/post.service.spec.ts
- frontend-implicaction/src/app/blog/services/post.service.ts
- frontend-implicaction/src/app/core/services/api-endpoints.service.ts
- frontend-implicaction/src/app/shared/enums/univers.ts
- frontend-implicaction/src/app/shared/models/uris.ts
- frontend-implicaction/src/styles.scss
* création du module blog
* création des composants blog-component, post-details, post-list et votebox
* ajout du userId dans le dto PostResponse
https://user-images.githubusercontent.com/4210719/140787937-43366c66-9a91-4801-ab6e-bf48e38e3162.mov
> RI-156: [discussion] affiche tous les posts

- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/SubredditController.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/SubredditRepository.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/SubredditService.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/utils/ApiUrls.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/SubredditControllerIntegrationTest.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/repository/AbstractContainerBaseTest.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/repository/SubredditRepositoryTest.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/repository/UserRepositoryTest.java
- frontend-implicaction/src/app/core/services/api-endpoints.service.ts
- frontend-implicaction/src/app/discussion/components/group-form/group-form.component.html
- frontend-implicaction/src/app/discussion/components/group-form/group-form.component.spec.ts
- frontend-implicaction/src/app/discussion/components/group-form/group-form.component.ts
- frontend-implicaction/src/app/discussion/components/option-menu/option-menu.component.html
- frontend-implicaction/src/app/discussion/components/option-menu/option-menu.component.spec.ts
- frontend-implicaction/src/app/discussion/components/option-menu/option-menu.component.ts
- frontend-implicaction/src/app/discussion/components/post-tile/post-tile.component.html
- frontend-implicaction/src/app/discussion/components/top-group-listing/top-group-listing.component.html
- frontend-implicaction/src/app/discussion/components/top-group-listing/top-group-listing.component.spec.ts
- frontend-implicaction/src/app/discussion/components/top-group-listing/top-group-listing.component.ts
- frontend-implicaction/src/app/discussion/components/top-group-skeleton/top-group-skeleton.component.html
- frontend-implicaction/src/app/discussion/components/top-group-skeleton/top-group-skeleton.component.spec.ts
- frontend-implicaction/src/app/discussion/components/top-group-skeleton/top-group-skeleton.component.ts
- frontend-implicaction/src/app/discussion/discussion.component.html
- frontend-implicaction/src/app/discussion/discussion.module.ts
- frontend-implicaction/src/app/discussion/model/group.ts
- frontend-implicaction/src/app/discussion/services/group.service.spec.ts
- frontend-implicaction/src/app/discussion/services/group.service.ts
- frontend-implicaction/src/app/shared/models/uris.ts
https://user-images.githubusercontent.com/4210719/140980661-0ff9ef5e-1f6e-4bc4-84a9-c7731944952a.mov
> RI-161: [discussion] permet de créer des groupes et affiche les groupes les plus actifs

- frontend-implicaction/src/app/admin/companies/companies.component.html
- frontend-implicaction/src/app/admin/companies/companies.component.ts
- frontend-implicaction/src/app/admin/companies/companies.module.ts
- frontend-implicaction/src/app/admin/companies/components/companies-table/companies-table.component.html
- frontend-implicaction/src/app/admin/companies/components/companies-table/companies-table.component.scss
- frontend-implicaction/src/app/admin/companies/components/companies-table/companies-table.component.ts
Précision: bug du header toujours présent, prochain fix possible avec la refonte de l'admin utilisateur
> RI-148 : ajoute un menu pour le listing des compagnies

- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/adapter/CommentAdapter.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/CommentDto.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/CommentRepository.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/CommentService.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/adapter/CommentAdapterTest.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/CommentControllerIntegrationTest.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/service/CommentServiceTest.java
- frontend-implicaction/src/app/config/constants.ts
- frontend-implicaction/src/app/core/services/api-endpoints.service.ts
- frontend-implicaction/src/app/discussion/components/comment-list/comment-list.component.html
- frontend-implicaction/src/app/discussion/components/comment-list/comment-list.component.scss
- frontend-implicaction/src/app/discussion/components/comment-list/comment-list.component.spec.ts
- frontend-implicaction/src/app/discussion/components/comment-list/comment-list.component.ts
- frontend-implicaction/src/app/discussion/components/comment-tile/comment-tile.component.html
- frontend-implicaction/src/app/discussion/components/comment-tile/comment-tile.component.spec.ts
- frontend-implicaction/src/app/discussion/components/comment-tile/comment-tile.component.ts
- frontend-implicaction/src/app/discussion/components/post-detail/post-detail.component.html
- frontend-implicaction/src/app/discussion/components/post-tile/post-tile.component.html
- frontend-implicaction/src/app/discussion/discussion.module.ts
- frontend-implicaction/src/app/discussion/model/comment-payload.ts
- frontend-implicaction/src/app/discussion/model/comment.ts
- frontend-implicaction/src/app/discussion/services/post.service.ts
- frontend-implicaction/src/app/shared/components/base-with-pagination-component/base-with-pagination.component.spec.ts
- frontend-implicaction/src/app/shared/components/base-with-pagination-component/base-with-pagination.component.ts
- frontend-implicaction/src/app/shared/components/header/header.component.html
- frontend-implicaction/src/app/shared/components/header/header.component.ts
- frontend-implicaction/src/app/shared/models/user.ts
- frontend-implicaction/src/app/shared/shared.module.ts
* creation du base-with-pagination.component
* création du comment-list.component
* création du comment-tile.component
* mise à jour du modèle comment pour y intégrer le userId, le userImageUrl et la durée + tests + adapters
> RI-160: permet la lecture des commentaires d'un post

- frontend-implicaction/src/app/discussion/components/post-detail/post-detail.component.html
- frontend-implicaction/src/app/discussion/components/post-list/post-list.component.html
- frontend-implicaction/src/app/discussion/components/post-list/post-list.component.ts
- frontend-implicaction/src/app/discussion/discussion-routing.module.ts
- frontend-implicaction/src/app/discussion/discussion.component.html
- frontend-implicaction/src/app/discussion/discussion.component.ts
* il intègre désormais la sidebar menu dans chacun de ses composants principaux
> RI-165: [discussion] réorganise le module discussion

- frontend-implicaction/src/app/admin/jobs/components/job-posting-form/job-posting-form.component.ts
* lors de la création d'un job, les entreprises ne remontaient pas
> fix: [admin/jobs] corrige un bug de la sidebar

- frontend-implicaction/src/app/admin/companies/components/companies-form/companies-form.component.ts
- frontend-implicaction/src/app/admin/companies/components/companies-table/companies-table.component.html
- frontend-implicaction/src/app/admin/companies/components/companies-table/companies-table.component.ts
- frontend-implicaction/src/app/admin/jobs/components/jobs-table/jobs-table.component.ts
- frontend-implicaction/src/app/discussion/components/comment-list/comment-list.component.ts
- frontend-implicaction/src/app/discussion/components/post-list/post-list.component.ts
- frontend-implicaction/src/app/job/components/jobs-list/jobs-list.component.ts
- frontend-implicaction/src/app/shared/components/base-with-pagination/base-with-pagination.component.spec.ts
- frontend-implicaction/src/app/shared/components/base-with-pagination/base-with-pagination.component.ts
- frontend-implicaction/src/app/shared/components/job-filter/job-filter.component.ts
- frontend-implicaction/src/app/shared/services/base-context-service.service.spec.ts
- frontend-implicaction/src/app/shared/services/base-context-service.service.ts
- frontend-implicaction/src/app/shared/services/company-context-service.service.spec.ts
- frontend-implicaction/src/app/shared/services/company-context-service.service.ts
- frontend-implicaction/src/app/shared/shared.module.ts
* modification du composant companies-table.component pour qu'il extends base-with-pagination.component
* ajout d'un toaster lors de l'ajout ou maj d'une entreprise
> RI-155: [admin/company] recharge le tableau lors de la création d'une nouvelle entreprise

- frontend-implicaction/src/app/app-routing.module.ts
- frontend-implicaction/src/app/board/board.component.html
- frontend-implicaction/src/app/board/board.component.spec.ts
- frontend-implicaction/src/app/board/board.component.ts
- frontend-implicaction/src/app/board/board.module.ts
- frontend-implicaction/src/app/shared/enums/univers.ts
* mise en place de la route
* ajout de l'univers associé
> RI-50: [job-board] ajoute le module board

- frontend-implicaction/src/app/board/board.component.html
- frontend-implicaction/src/app/board/board.component.scss
- frontend-implicaction/src/app/board/board.component.ts
- frontend-implicaction/src/app/board/board.module.ts
- frontend-implicaction/src/app/board/models/job-apply.ts
https://user-images.githubusercontent.com/4210719/142742505-e3dd2a09-3136-47e5-9186-71480c86931c.mov
> RI-190: [job-board] permet de déplacer une offre en drag & drop

- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/JobApplicationService.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/service/JobApplicationServiceTest.java
- frontend-implicaction/src/app/board/board.component.html
- frontend-implicaction/src/app/board/board.module.ts
- frontend-implicaction/src/app/board/components/apply-card/apply-card.component.html
- frontend-implicaction/src/app/board/components/apply-card/apply-card.component.ts
- frontend-implicaction/src/app/board/components/card-menu/card-menu.component.html
- frontend-implicaction/src/app/board/components/card-menu/card-menu.component.scss
- frontend-implicaction/src/app/board/components/card-menu/card-menu.component.spec.ts
- frontend-implicaction/src/app/board/components/card-menu/card-menu.component.ts
* mise à jour de la date de dernière modifs
> RI-195: [job-board] ajoute un menu d'actions aux cards

- frontend-implicaction/src/app/admin/jobs/admin-jobs.module.ts
- frontend-implicaction/src/app/admin/jobs/components/jobs-table/jobs-table.component.html
- frontend-implicaction/src/app/admin/jobs/components/jobs-table/jobs-table.component.ts
On peut maintenant sélectionner une ou plusieurs offres dans l'admin
> RI-137: [admin/jobs] permet la sélection de plusieurs offres

- frontend-implicaction/src/app/admin/users/components/users-table/table-users.component.html
- frontend-implicaction/src/app/admin/users/components/users-table/table-users.component.ts
On peut maintenant sélectionner plusieurs utilisateurs dans l'admin
> RI-171: [admin/users] permet la selection de plusieurs utilisateurs

- frontend-implicaction/src/app/admin/companies/components/companies-table/companies-table.component.html
- frontend-implicaction/src/app/admin/companies/components/companies-table/companies-table.component.ts
On peut maintenant sélectionner plusieurs entreprises dans l'admin
> RI-138: [admin/companies] permet la sélection de plusieurs entreprises

- frontend-implicaction/src/app/admin/users/components/users-table/table-users.component.html
- frontend-implicaction/src/app/admin/users/components/users-table/table-users.component.ts
- frontend-implicaction/src/app/admin/users/users.module.ts
Bug du ng-template des tables toujours présents
> RI-154 : modifie la structure et le design de l'édition des utilisateurs

- frontend-implicaction/src/app/admin/companies/components/companies-table/companies-table.component.ts
- frontend-implicaction/src/app/admin/jobs/components/jobs-table/jobs-table.component.html
- frontend-implicaction/src/app/admin/jobs/components/jobs-table/jobs-table.component.ts
- frontend-implicaction/src/app/job/components/jobs-list/jobs-list.component.ts
- frontend-implicaction/src/app/shared/components/base-with-pagination/base-with-pagination.component.spec.ts
- frontend-implicaction/src/app/shared/components/base-with-pagination/base-with-pagination.component.ts
> RI-199: [admin/front] refacto de la méthode getFilterFromQueryParams du composant BaseWithPaginationComponent

- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/adapter/GroupAdapter.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/GroupController.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/UserController.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/GroupDto.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/GroupRepository.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/GroupService.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/PostService.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/UserService.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/utils/ApiUrls.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/utils/Message.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/adapter/GroupAdapterTest.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/UserControllerTest.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/repository/GroupRepositoryTest.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/service/GroupServiceTest.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/service/PostServiceTest.java
- frontend-implicaction/src/app/core/services/api-endpoints.service.ts
- frontend-implicaction/src/app/discussion/components/top-group-listing/top-group-listing.component.html
- frontend-implicaction/src/app/discussion/components/top-group-listing/top-group-listing.component.ts
- frontend-implicaction/src/app/discussion/discussion.module.ts
- frontend-implicaction/src/app/discussion/services/group.service.ts
- frontend-implicaction/src/app/shared/models/uris.ts
- frontend-implicaction/src/app/user/services/user.service.ts
C'est une premiere ebauche, j'ai commencé à travailler sur pouvoir rejoindre un groupe depuis une discussion mais jsp si c'est compris dans la jira --> la subtilité c'est que l'ajout à partir du listing des meilleurs groupe se fait via l'id, mais depuis une discussion je ne récupère que le nom du groupe. Est ce que je me base sur le nom du groupe pour le listing des top groupes ?
Il faudrait aussi voir le css du bouton d'ajout, j'ai pas trouvé mieux (faut pas trop me demander de front)
> RI-217: rejoint un groupe

- frontend-implicaction/src/app/job/components/jobs-list/jobs-list.component.html
- frontend-implicaction/src/app/job/components/jobs-list/jobs-list.component.ts
> RI-219: permet d'ajouter une offre depuis la page offre d'emploi

- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/adapter/GroupAdapter.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/dto/GroupDto.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/adapter/GroupAdapterTest.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/UserControllerTest.java
- frontend-implicaction/src/app/admin/groups/pending-group-table/pending-group-table.component.html
- frontend-implicaction/src/app/admin/jobs/components/pending-job-table/pending-job-table.component.html
- frontend-implicaction/src/app/admin/users/components/pending-user-table/pending-user-table.component.html
- frontend-implicaction/src/app/discussion/components/group-card/group-card.component.html
- frontend-implicaction/src/app/discussion/components/group-card/group-card.component.scss
- frontend-implicaction/src/app/discussion/components/group-card/group-card.component.spec.ts
- frontend-implicaction/src/app/discussion/components/group-card/group-card.component.ts
- frontend-implicaction/src/app/discussion/components/group-list/group-list.component.html
- frontend-implicaction/src/app/discussion/components/group-list/group-list.component.scss
- frontend-implicaction/src/app/discussion/components/group-list/group-list.component.spec.ts
- frontend-implicaction/src/app/discussion/components/group-list/group-list.component.ts
- frontend-implicaction/src/app/discussion/components/top-group-listing/top-group-listing.component.html
- frontend-implicaction/src/app/discussion/discussion-routing.module.ts
- frontend-implicaction/src/app/discussion/discussion.module.ts
- frontend-implicaction/src/app/discussion/model/group.ts
- frontend-implicaction/src/app/job/components/jobs-list/jobs-list.component.html
> RI-220: [discussion] liste les groupes 

- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/controller/JobPostingController.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/JobPostingRepositoryCustom.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/repository/impl/JobPostingRepositoryImpl.java
- backend-implicaction/src/main/java/com/dynonuggets/refonteimplicaction/service/JobPostingService.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/controller/JobsPostingControllerTest.java
- backend-implicaction/src/test/java/com/dynonuggets/refonteimplicaction/service/JobPostingServiceTest.java
- frontend-implicaction/src/app/admin/jobs/admin-jobs.component.html
- frontend-implicaction/src/app/admin/jobs/admin-jobs.component.ts
- frontend-implicaction/src/app/auth/components/login/login.component.ts
- frontend-implicaction/src/app/home/components/post-card/post-card.component.html
- frontend-implicaction/src/app/home/components/post-card/post-card.component.scss
- frontend-implicaction/src/app/job/components/jobs-list/jobs-list.component.html
- frontend-implicaction/src/app/job/components/jobs-list/jobs-list.component.scss
- frontend-implicaction/src/app/job/components/jobs-list/jobs-list.component.ts
- frontend-implicaction/src/app/job/models/job-criteria-filter.ts
- frontend-implicaction/src/app/shared/components/header/header.component.ts
- frontend-implicaction/src/app/shared/components/job-filter/job-filter.component.html
- frontend-implicaction/src/app/shared/components/job-filter/job-filter.component.ts
- frontend-implicaction/src/app/shared/shared.module.ts
- frontend-implicaction/src/styles.scss
* refacto de l'admin job qui hérite désormais du composant job-list-component
* changement des toasters de login et logout pour les remettre en français
* fix du style des dropdown pour qu'ils affichent une border sauf si no-outline
* les cards des derniers posts de l'accueil ont désormais une hauteur fixe
> RI-48: [jobs/filter] permet de filter par secteur d'activité
